services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
